name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              timeout-minutes: 2

            - name: Install dependencies
              run: npm install
              timeout-minutes: 10

            - name: Lint
              run: npx eslint --ext .ts .
              timeout-minutes: 5

            - name: Test
              run: npm test
              timeout-minutes: 5

            - name: Start Server
              run: npx ts-node index.ts &
              timeout-minutes: 2

            - name: Stop Server
              run: pkill -f "ts-node index.ts"
              timeout-minutes: 2
